# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LogosWallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LogosWallet
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'NotificationBannerSwift', '1.6.3'
  pod 'Moya', '~> 11.0'
  pod 'lottie-ios'
  pod 'Sodium', :git => 'https://github.com/nebyark/swift-sodium'
  pod 'SSZipArchive'
  pod 'Starscream'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MQTTClient/Websocket', :git => 'https://github.com/nebyark/MQTT-Client-Framework'
end

target 'LogosWalletTests' do
  use_frameworks!
  pod 'RealmSwift'
end